[project]
name = "BEoRN"
version = "2.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

# include in docs
dependencies = [
    "numpy>=1.26",
    "scipy>=1.15.2",
    "h5py>=3.13.0",
    "mpi4py>=4.1.1",
    "astropy>=7.0.1",
    "matplotlib>=3.10.1",
    "pylians>=0.12",
    "tools21cm>=2.2.10",
    "tqdm>=4.0",
]
# end include in docs


[project.optional-dependencies]
extra = [
    "21cmfast>=3.4.0,<4",
    "hmf>=3.4",
]


[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
beorn = ["input_data/*.dat", "files/*.dat"]

[project.urls]
Homepage = "https://beorn.cosmic-reionization.github.io"
Documentation = "https://beorn.cosmic-reionization.github.io"
Repository = "https://github.com/cosmic-reionization/beorn.git"
