from pathlib import Path
import time
import h5py
import logging
import numpy as np
from tqdm.auto import tqdm

from .base import BaseLoader
from ..structs import HaloCatalog, Parameters
from ..io import Handler

logger = logging.getLogger(__name__)


class Py21cmFastLoader(BaseLoader):
    """Loader for data generated by py21cmfast.

    Can either load pre-existing HDF5 files from a known directory, or
    generate them on the fly by calling :meth:`generate`.

    Args:
        parameters (Parameters): Simulation and cosmology parameters.
        file_root (Path, optional): Directory containing pre-generated
            ``haloes_z*.h5`` and ``densities_z*.h5`` files. If ``None``,
            call :meth:`generate` before loading data.
    """

    def __init__(self, parameters: Parameters, file_root: Path = None):
        super().__init__(parameters)
        self.file_root = Path(file_root) if file_root is not None else None

    @property
    def redshifts(self) -> np.ndarray:
        """Redshift grid from simulation parameters (descending order)."""
        return self.parameters.solver.redshifts

    def generate(self, handler: Handler) -> None:
        """Run py21cmfast to generate halo catalogs and density fields.

        Produces ``haloes_z{z}.h5`` and ``densities_z{z}.h5`` files for
        every redshift in ``parameters.solver.redshifts`` and stores them
        under a hash-keyed subdirectory of ``handler.file_root``. Sets
        ``self.file_root`` so that :meth:`load_halo_catalog` and
        :meth:`load_density_field` can be called immediately after.

        Args:
            handler (Handler): IO handler that determines the storage location.

        Raises:
            ImportError: If ``py21cmfast`` is not installed.
        """
        try:
            import py21cmfast as p21c
        except ImportError:
            raise ImportError(
                'Generating data with py21cmfast requires additional dependencies. '
                'Install beorn with the extra package set: `pip install beorn[extra]` '
                'or see https://github.com/21cmfast/21cmFAST/.'
            )

        start_time = time.process_time()

        file_root = handler.file_root / f"py21cmfast_{self.parameters.unique_hash()}"
        file_root.mkdir(parents=True, exist_ok=True)

        n_redshifts = len(self.parameters.solver.redshifts)
        logger.info(
            f'Generating matter and halo data with py21cmfast for {n_redshifts} redshift snapshots.\n'
            f'  Output directory : {file_root}\n'
            f'  Grid             : HII_DIM={self.parameters.simulation.Ncell}, DIM={self.parameters.simulation.Ncell * 3}\n'
            f'  Box size         : {self.parameters.simulation.Lbox:.1f} Mpc/h '
            f'({self.parameters.simulation.Lbox / self.parameters.cosmology.h:.1f} Mpc)\n'
            f'  Redshift range   : z={self.parameters.solver.redshifts[-1]:.2f} - {self.parameters.solver.redshifts[0]:.2f}\n'
            f'  Threads          : {self.parameters.simulation.cores}'
        )

        user_params = p21c.UserParams(
            HII_DIM=self.parameters.simulation.Ncell,
            DIM=self.parameters.simulation.Ncell * 3,
            BOX_LEN=self.parameters.simulation.Lbox / self.parameters.cosmology.h,
            USE_INTERPOLATION_TABLES=True,
            N_THREADS=self.parameters.simulation.cores,
        )

        cosmo_params = p21c.CosmoParams(
            SIGMA_8=self.parameters.cosmology.sigma_8,
            hlittle=self.parameters.cosmology.h,
            OMm=self.parameters.cosmology.Om,
            OMb=self.parameters.cosmology.Ob,
            POWER_INDEX=self.parameters.cosmology.ns,
        )

        global_params = {
            "INITIAL_REDSHIFT": 300,
            "CLUMPING_FACTOR": 2.0,
        }

        logger.info('Computing initial conditions...')
        ic_start = time.process_time()
        IC = p21c.initial_conditions(
            user_params=user_params,
            cosmo_params=cosmo_params,
            random_seed=self.parameters.simulation.random_seed,
            direc=str(file_root),
        )
        logger.info(f'Initial conditions done in {time.process_time() - ic_start:.1f}s.')

        with p21c.global_params.use(**global_params):
            for redshift in tqdm(self.parameters.solver.redshifts, desc='py21cmfast snapshots', unit='snapshot'):
                halo_fname = f'haloes_z{redshift}.h5'
                field_fname = f'densities_z{redshift}.h5'

                z_start = time.process_time()
                perturbed_field = p21c.perturb_field(
                    redshift=redshift, init_boxes=IC, direc=str(file_root)
                )
                halo_list = p21c.perturb_halo_list(
                    redshift=redshift, init_boxes=IC, direc=str(file_root)
                )

                halo_list.write(direc=file_root, fname=halo_fname)
                perturbed_field.write(direc=file_root, fname=field_fname)
                logger.debug(
                    f'z={redshift:.3f}: {len(halo_list.halo_masses)} halos, '
                    f'wrote {halo_fname} and {field_fname} '
                    f'({time.process_time() - z_start:.1f}s)'
                )

        self.file_root = file_root
        logger.info(
            f'Finished generating data in {time.process_time() - start_time:.1f}s. '
            f'Files stored at: {file_root}'
        )

    def load_halo_catalog(self, redshift_index: int) -> HaloCatalog:
        self._require_file_root()
        redshift = self.redshifts[redshift_index]
        path = self.file_root / f'haloes_z{redshift}.h5'

        with h5py.File(path, 'r') as f:
            haloes = f['PerturbHaloField']
            m = np.asarray(haloes['halo_masses'])
            positions = np.asarray(haloes['halo_coords'])

        scaling = float(self.parameters.simulation.Lbox / self.parameters.simulation.Ncell)
        return HaloCatalog(
            masses=m * self.parameters.cosmology.h,
            positions=positions * scaling,
            parameters=self.parameters,
        )

    def load_density_field(self, redshift_index: int) -> np.ndarray:
        self._require_file_root()
        redshift = self.redshifts[redshift_index]
        path = self.file_root / f'densities_z{redshift}.h5'

        with h5py.File(path, 'r') as f:
            return f['PerturbedField']['density'][:]

    def load_rsd_fields(self, redshift_index: int):
        raise NotImplementedError("RSD fields are not yet implemented for Py21cmFastLoader.")

    def _require_file_root(self):
        if self.file_root is None:
            raise RuntimeError(
                "No data directory set. Either call generate(handler) to produce data "
                "with py21cmfast, or pass file_root to the constructor to load existing files."
            )
